apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  parallelism: 10
  completions: 100
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo",  "ok"]
      restartPolicy: Never