apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/X-X-X-X/resourceGroups/MC_rg-aks-lab-azdisk-zones_aks-lab-azdisk-zones_westeurope/providers/Microsoft.Compute/disks/myAKSDisk3
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-azuredisk3
  storageClassName: managed-csi