apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-03-23T14:42:20Z"
  generation: 1
  labels:
    app: demo
  name: demo
  namespace: default
  resourceVersion: "345156"
  uid: 1a7a2458-df98-4d09-bd3f-800ee1b8f61f
spec:
  progressDeadlineSeconds: 600
  replicas: 20
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
        args:
          - --subscriptionid=$SUBSCRIPTION_ID
          - --clientid=$IDENTITY_CLIENT_ID
          - --resourcegroup=$IDENTITY_RESOURCE_GROUP
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30