apiVersion: v1
kind: Pod
metadata:
  generateName: out-of-cpu-test-
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: kind-worker
  containers:
  - image: ubuntu:18.04
    name: ubuntu
    command: ["echo", "hello"]
    resources:
      requests:
        cpu: 1
        memory: 100M