apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-file
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi